### ISSUE TITLE
DALQueryError on 4. TAP: Using the TAP to cross-correlate our objects with a catalog

### ISSUE THREAD

**Issue by JosephKarpinski** [NASA-NAVO/aas_workshop_2020_winter#13]
Error when trying to run query: TAP: Using the TAP to cross-correlate our objects with a catalog

<img width="1305" alt="CS_Catalog_error" src="https://user-images.githubusercontent.com/37123616/106307276-26dcff80-622d-11eb-94a3-89d503f3bf57.png">

**Comment by stargaser** [comment]
Hello @JosephKarpinski , a few notes:

- We are now keeping our workshop materials at https://github.com/NASA-NAVO/navo-workshop which we used for our most recent workshop at AAS 237 in early January 2021. We will use that repository instead of making a new one for each workshop.
- I tried this notebook in a Binder session with pyvo 1.1 and it worked for me, three times. It might be an intermittent issue with the underlying service, and may work for you when re-tried.

**Comment by JosephKarpinski** [comment]
Hi,

Tried the version 
> 
> at https://github.com/NASA-NAVO/navo-workshop .
Same issue.

The problem query uses uploads={‘mysources’: ‘data/my_sources.xml’}

What is that? 

Guessing that is a workshop environment dependency that doesn’t exist on someone’s home computer?

The source of the DALQueryError, Errors detected in query preprocessing...

There could be many astronomers/students from all over that have downloaded your code
and are running into similar problems...

**Comment by stargaser** [comment]
The notebook assumes that the repository has been cloned or otherwise downloaded. The file is at https://github.com/NASA-NAVO/aas_workshop_2020_winter/blob/master/data/my_sources.xml.

**Comment by JosephKarpinski** [comment]
That worked!

Thank you.

Joseph Karpinski 
JosephKarpinski@hotmail.com
